---
title: "Figures, manuscript 2"
output: 
  html_document:
    theme: united
    number_sections: true
    toc: true
    toc_depth: 2
    toc_float: 
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE,message=FALSE,warning=FALSE)
library(tidyverse)
library(readr)
library(knitr)
library(emdbook)
setwd("~/Desktop/Publications/CDC/")
```

# Private Sector Plots {.tabset}


## DTaP Private Sector

```{r}
dtap.priv.int <- function(x) (1.053+2.361/(1+x))
dtap.pub.int <- function(x) (1.396+1.526/(1+x))
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(aes(linetype="Private"),fun=dtap.priv.int,size=1.5) +
  stat_function(aes(linetype="Public"),fun=dtap.pub.int,size=1.5) +
  scale_linetype_manual(name="Sector",values=c("Public"=2,"Private"=1), 
                  guide = guide_legend(override.aes=aes(fill=NA))) + 
  xlab("Product similarity") +
  ylab("Intercept (million units)") +
 # ggtitle("DTaP",subtitle=" Demand curve intercepts") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,4))+
  theme_classic() +
   theme(text=element_text(size=20),
     axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)))
```

```{r}
dtap.price <- function(x) (34.143+10.53*x)*(1-x)/(2-x)
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(fun=dtap.price,colour="black",size=1.5) +
  xlab("Product similarity") +
  ylab("Price (USD)") +
  #ggtitle("DTaP",subtitle="Private Sector Price") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,20))+
  theme_classic() +
   
   theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)),
        text=element_text(size=20))
```

```{r}
fun.quant <- function(x) (3.414+1.053*x)/((2-x)*(1+x))
fun.U <- function(x) (3.414+1.053*x)/x*(1-2*(1-x)^0.5/((2-x)*(1+x)^0.5))
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(aes(linetype="Quantity"),fun=fun.quant,colour="black",size=1.5) +
  stat_function(aes(linetype="Capacity"),fun=fun.U,colour="black",size=1.5) +
  scale_linetype_manual(name="Parameter",values=c("Capacity"=2,"Quantity"=1), 
                  guide = guide_legend(override.aes=aes(fill=NA))) +
  xlab("Product similarity") +
  ylab("Quantity (million units)") +
  #ggtitle("DTaP",subtitle="Private Sector Quantity and Minimum Private Sector Capacity") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,4))+
  theme_classic() +
   
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)),
        text=element_text(size=20))
```


## HepB Private Sector

```{r}
hepb.priv.int <- function(x) (1.6745+2.2466/(1+x))
hepb.pub.int <- function(x) (2.2197+1.1023/(1+x))
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(fun=hepb.priv.int,linetype=1) +
  stat_function(fun=hepb.pub.int,linetype=2) +
  xlab("Product similarity") +
  ylab("Intercept (millions of units)") +
  ggtitle("HepB",subtitle="Demand curve intercepts") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,4))+
  theme_classic() +
   
   theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)))
```

```{r}
hepb.price <- function(x) hepb.priv.int(x)*(1+x)*(1-x)/((2-x))*10
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(fun=hepb.price,colour="black") +
  xlab("Product similarity") +
  ylab("Price (USD)") +
  ggtitle("HepB",subtitle="Private Sector Price") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,20))+
  theme_classic() +
   
   theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)))
```

```{r}
hepb.quant <- function(x) hepb.price(x)*10^(-1)/((1+x)*(1-x))
hepb.U <- function(x) hepb.priv.int(x)*(1+x)/x*(1-2*(1-x)^0.5/((2-x)*(1+x)^0.5))
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(fun=fun.quant,colour="black",linetype=1) +
  stat_function(fun=fun.U,colour="black",linetype=2) +
  xlab("Product similarity") +
  ylab("Quantity (millions of units)") +
  ggtitle("HepB",subtitle=" Private Sector Quantity and Minimum Private Sector Capacity") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,4.5))+
  theme_classic() +
   
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)))
```


## Both Private Sectors
```{r}

ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(aes(linetype="Private",color="DTaP"),fun=dtap.priv.int) +
  stat_function(aes(linetype="Private",color="HepB"),fun=hepb.priv.int) +
  stat_function(aes(linetype="Public",color="DTaP"),fun=dtap.pub.int) +
  stat_function(aes(linetype="Public",color="HepB"),fun=hepb.pub.int) +
  xlab("Product similarity") +
  ylab("Intercept (millions of units)") +
  #ggtitle("Demand curve intercepts") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,4))+
  scale_colour_manual(name="Vaccine",values=c("HepB"="red","DTaP"="black"), 
                  guide = guide_legend(override.aes=aes(fill=NA))) + 
  scale_linetype_manual(name="Sector",values=c("Public"=2,"Private"=1), 
                  guide = guide_legend(override.aes=aes(fill=NA))) + 
  theme_classic() +
   theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), 
         axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)),
        text = element_text(size=25))
```

```{r}
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(aes(color="HepB"),fun=hepb.price) +
  stat_function(aes(color="DTaP"),fun=dtap.price) +
  xlab("Product similarity") +
  ylab("Price (USD)") +
  #ggtitle("DTaP",subtitle="Private Sector Price") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  scale_y_continuous(expand=c(0,0),limits=c(0,20))+
  theme_classic() +
  scale_colour_manual(name="Vaccine",values=c("HepB"="red","DTaP"="black"), 
                  guide = guide_legend(override.aes=aes(fill=NA))) + 
   theme(axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)),
        text = element_text(size=25))
```
```{r}
ggplot(data=data.frame(x=0),mapping=aes(x=x)) + 
  stat_function(aes(linetype="Quantity",color="DTaP"),fun=fun.quant) +
  stat_function(aes(linetype="Quantity",color="HepB"),fun=hepb.quant) +
  stat_function(aes(linetype="Capacity",color="DTaP"),fun=fun.U) +
  stat_function(aes(linetype="Capacity",color="HepB"),fun=hepb.U) +
  scale_colour_manual(name="Vaccine",values=c("HepB"="red","DTaP"="black"), 
                  guide = guide_legend(override.aes=aes(fill=NA))) + 
  scale_linetype_manual(name="Parameter",values=c("Capacity"=2,"Quantity"=1), 
                  guide = guide_legend(override.aes=aes(fill=NA))) + 
  xlab("Product similarity") +
  ylab("Quantity (millions of units)") +
  #ggtitle("DTaP",subtitle="Private Sector Quantity and Minimum Private Sector Capacity") +
  scale_x_continuous(expand=c(0,0),limits=c(0,1))+
  #scale_y_continuous(expand=c(0,0),limits=c(0,4))+
  theme_classic() +
   
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)), axis.text.x = element_text(margin = margin(t=10, r = 5, b = 0, l = 0)),
        axis.text.y = element_text(margin = margin(t=10, r = 10, b = 10, l = 0)),
        text = element_text(size=25))
```


# Feasible Region Plots {.tabset}

## DTaP Feasible Region

TODO


```{r,echo=FALSE,message=FALSE,warning=FALSE,eval=FALSE}
# inputs
#    market = "D" or "H" for DTaP or HepB
#    prod_sim = product similarity
#    mi_capacity = manuf. i capacity
#    mi_profit = manuf. i target profit
#    demand
#    xmax, ymax = maximum limit of viewing pane

# parse arguments
prod_sim <- 0.25 #as.numeric(prod_sim)
m1_capacity <- 4034000 #as.numeric(m1_capacity)
m2_capacity <- 4034000# as.numeric(m2_capacity)
m1_profit <- 38500000#as.numeric(m1_profit)
m2_profit <- 43500000#as.numeric(m2_profit)
demand <- 4034000#as.numeric(demand)
xmax <- 4000000#as.numeric(xmax)
ymax <- 4000000#as.numeric(ymax)
m1_infl <- 100
m2_infl <- 100

# if market == D
priv_price <- (34.143+10.53*prod_sim)*(1-prod_sim)/(2-prod_sim)
priv_quant <- (3.414+1.053*prod_sim)/((1+prod_sim)*(2-prod_sim))*10^6
alpha_pub <- (1.396*(1+prod_sim)+1.526)*10^6
U <- (3.414+1.053*prod_sim)/prod_sim*
    (1-2*(1-prod_sim)^0.5/((1+prod_sim)^0.5*(2-prod_sim)))*10^6

# target profit curves
m1_prof <- emdbook::curve3d(
  (alpha_pub-y-prod_sim*x)*y*10^(-5)-m1_profit+priv_price*priv_quant,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_prof$z) <- list(m1_prof$x, m1_prof$y)
m1_prof_df <- reshape2::melt(m1_prof$z)
m2_prof <- emdbook::curve3d(
  (alpha_pub-x-prod_sim*y)*x*10^(-5)-m2_profit+priv_price*priv_quant,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_prof$z) <- list(m2_prof$x, m2_prof$y) # m2 = gsk
m2_prof_df <- reshape2::melt(m2_prof$z)

# public sector demand threshold
dem <- emdbook::curve3d(
  (x+y-0.57*demand),
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none")
dimnames(dem$z) <- list(dem$x, dem$y)
dem_df <- reshape2::melt(dem$z)

# public sector price non-negativity
m1_price <- emdbook::curve3d(
  alpha_pub-y-prod_sim*x,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_price$z) <- list(m1_price$x, m1_price$y)
m1_price_df <- reshape2::melt(m1_price$z)
m2_price <- emdbook::curve3d(
  alpha_pub-x-prod_sim*y,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_price$z) <- list(m2_price$x, m2_price$y)
m2_price_df <- reshape2::melt(m2_price$z)

# public sector price inflation bounds
m1_price_infl <- emdbook::curve3d(
  10^(-5)*(alpha_pub-y-prod_sim*x)-m1_infl,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_price_infl$z) <- list(m1_price_infl$x, m1_price_infl$y)
m1_price_infl_df <- reshape2::melt(m1_price_infl$z)
m2_price_infl <- emdbook::curve3d(
  10^(-5)*(alpha_pub-x-prod_sim*y)-m2_infl,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_price_infl$z) <- list(m2_price_infl$x, m2_price_infl$y)
m2_price_infl_df <- reshape2::melt(m2_price_infl$z)


# production capacities
m1_cap <- emdbook::curve3d(
  x-m1_capacity+U,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_cap$z) <- list(m1_cap$x, m1_cap$y)
m1_cap_df <- reshape2::melt(m1_cap$z)
m2_cap <- emdbook::curve3d(
  y-m2_capacity+U,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_cap$z) <- list(m2_cap$x, m2_cap$y)
m2_cap_df <- reshape2::melt(m2_cap$z)

dummy.data <- data.frame(x=1,y=2)
dummy.data %>% 
ggplot(aes(x=x,y=y)) +
geom_contour(data=m1_prof_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Target profit"),
             breaks=0,
             colour="black"
             ) +
geom_contour(data=m2_prof_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Target profit"),
             breaks=0,
             colour="black"
             ) +
geom_contour(data=dem_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Demand"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m1_price_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
 geom_contour(data=m2_price_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m1_price_infl_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
 geom_contour(data=m2_price_infl_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m1_cap_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Public sector capacity"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m2_cap_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Public sector capacity"),
             breaks=0,
             colour="black",
             size=1
             ) +
scale_y_continuous(expand=c(0,0),limits = c(0,ymax))+
scale_x_continuous(expand=c(0,0),limits = c(0,xmax))+
xlab("M2 Public Sector Quantity (millions)") +
ylab("M1 Public Sector Quantity (millions)") +
theme_classic() +
theme(text = element_text(size=20),
      axis.text.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))) +
scale_linetype_manual("Constraint",
      values=c("Target profit"=1,"Demand"=2,"Public sector price bound"=3, 
               "Public sector capacity"=4)) +
guides(fill = guide_legend(keywidth = 1, keyheight = 1),
  linetype=guide_legend(keywidth = 3, keyheight = 1),
  colour=guide_legend(keywidth = 3, keyheight = 1))


```

## HepB Feasible Region

TODO

```{r,echo=FALSE,message=FALSE,warning=FALSE,eval=FALSE}
# inputs
#    market = "D" or "H" for DTaP or HepB
#    prod_sim = product similarity
#    mi_capacity = manuf. i capacity
#    mi_profit = manuf. i target profit
#    demand
#    xmax, ymax = maximum limit of viewing pane

# parse arguments
prod_sim <- 0.25 #as.numeric(prod_sim)
m1_capacity <- 7032000 #as.numeric(m1_capacity)
m2_capacity <- 7032000# as.numeric(m2_capacity)
m1_profit <- 58200000#as.numeric(m1_profit)
m2_profit <- 55100000#as.numeric(m2_profit)
demand <- 7032000#as.numeric(demand)
xmax <- 6000000#as.numeric(xmax)
ymax <- 6000000#as.numeric(ymax)
m1_infl <- 100
m2_infl <- 100

# if market == D
priv_price <-(39.211+16.745*prod_sim)*(1-prod_sim)/(2-prod_sim)
priv_quant <- (3.9211+1.6745*prod_sim)/((1+prod_sim)*(2-prod_sim))*10^6
alpha_pub <- (2.2197*(1+prod_sim)+1.1023)*10^6
U <- (3.9211+1.6745*prod_sim)/prod_sim*
    (1-2*(1-prod_sim)^0.5/((1+prod_sim)^0.5*(2-prod_sim)))*10^6

# target profit curves
m1_prof <- emdbook::curve3d(
  (alpha_pub-y-prod_sim*x)*y*10^(-5)-m1_profit+priv_price*priv_quant,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_prof$z) <- list(m1_prof$x, m1_prof$y)
m1_prof_df <- reshape2::melt(m1_prof$z)
m2_prof <- emdbook::curve3d(
  (alpha_pub-x-prod_sim*y)*x*10^(-5)-m2_profit+priv_price*priv_quant,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_prof$z) <- list(m2_prof$x, m2_prof$y) # m2 = gsk
m2_prof_df <- reshape2::melt(m2_prof$z)

# public sector demand threshold
dem <- emdbook::curve3d(
  (x+y-0.57*demand),
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none")
dimnames(dem$z) <- list(dem$x, dem$y)
dem_df <- reshape2::melt(dem$z)

# public sector price non-negativity
m1_price <- emdbook::curve3d(
  alpha_pub-y-prod_sim*x,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_price$z) <- list(m1_price$x, m1_price$y)
m1_price_df <- reshape2::melt(m1_price$z)
m2_price <- emdbook::curve3d(
  alpha_pub-x-prod_sim*y,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_price$z) <- list(m2_price$x, m2_price$y)
m2_price_df <- reshape2::melt(m2_price$z)

# public sector price inflation bounds
m1_price_infl <- emdbook::curve3d(
  10^(-5)*(alpha_pub-y-prod_sim*x)-m1_infl,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_price_infl$z) <- list(m1_price_infl$x, m1_price_infl$y)
m1_price_infl_df <- reshape2::melt(m1_price_infl$z)
m2_price_infl <- emdbook::curve3d(
  10^(-5)*(alpha_pub-x-prod_sim*y)-m2_infl,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_price_infl$z) <- list(m2_price_infl$x, m2_price_infl$y)
m2_price_infl_df <- reshape2::melt(m2_price_infl$z)


# production capacities
m1_cap <- emdbook::curve3d(
  x-m1_capacity+U,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m1_cap$z) <- list(m1_cap$x, m1_cap$y)
m1_cap_df <- reshape2::melt(m1_cap$z)
m2_cap <- emdbook::curve3d(
  y-m2_capacity+U,
  xlim=c(-100000,xmax),
  ylim=c(-100000,ymax),
  sys3d="none"
)
dimnames(m2_cap$z) <- list(m2_cap$x, m2_cap$y)
m2_cap_df <- reshape2::melt(m2_cap$z)

dummy.data <- data.frame(x=1,y=2)
dummy.data %>% 
ggplot(aes(x=x,y=y)) +
geom_contour(data=m1_prof_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Target profit"),
             breaks=0,
             colour="black"
             ) +
geom_contour(data=m2_prof_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Target profit"),
             breaks=0,
             colour="black"
             ) +
geom_contour(data=dem_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Demand"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m1_price_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
 geom_contour(data=m2_price_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m1_price_infl_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
 geom_contour(data=m2_price_infl_df,
              aes(x=Var1,y=Var2,z=value,
                  linetype="Public sector price bound"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m1_cap_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Public sector capacity"),
             breaks=0,
             colour="black",
             size=1
             ) +
geom_contour(data=m2_cap_df,
             aes(x=Var1,y=Var2,z=value,
                 linetype="Public sector capacity"),
             breaks=0,
             colour="black",
             size=1
             ) +
scale_y_continuous(expand=c(0,0),limits = c(0,ymax))+
scale_x_continuous(expand=c(0,0),limits = c(0,xmax))+
xlab("M2 Public Sector Quantity (millions)") +
ylab("M1 Public Sector Quantity (millions)") +
theme_classic() +
theme(text = element_text(size=20),
      axis.text.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))) +
scale_linetype_manual("Constraint",
      values=c("Target profit"=1,"Demand"=2,"Public sector price bound"=3, 
               "Public sector capacity"=4)) +
guides(fill = guide_legend(keywidth = 1, keyheight = 1),
  linetype=guide_legend(keywidth = 3, keyheight = 1),
  colour=guide_legend(keywidth = 3, keyheight = 1))


```
